### ISSUE TITLE
Unknown component type 'undefined'

### ISSUE THREAD

**Issue by Falconerd** [makrjs/makr#7]
Not sure if I'm being dense, but I've attempted to use this library with both rollup and webpack to no avail. With both of those build tools I'm getting the same error: Unknown component type 'undefined'.

``` js
import makr from 'makr';

class Body {
  constructor(x, y) {
    this.x = x
    this.y = y
    this.dx = 0
    this.dy = 0
  }
}

class Display {
  constructor(img) {
    this.img = img
  }
}

// Create the entity manager
const em = makr(Body, Display)

const entity = em.create();
entity.add(Body); // error
entity.add(Display);
```

I should also mention that I'm using Babel 6 to transpile. I'm going to attempt to use 6to5 as I read in a forum post that you were using that.

Edit: Nevermind, it seems that 6to5 is actally Babel. Didn't realise that.

**Comment by Falconerd** [comment]
I made a derp. I checked the tests and realised that you must instantiate the components when adding them... That makes total sense.

``` js
const entity = em.create();
entity.add(new Body(5, 5));
```

**Comment by ooflorent** [comment]
@Falconerd I'm working on a new version and was thinking about something like this:

``` js
entity.assign(Body)
entity.assign(Position, {x: 1, y: 2})
```

In this example, `Body` and `Position` would no longer be functions but integers. It would provide a huge speedup and allow easier mask definition:

``` js
em.query(Body | Position)
```

**Comment by Falconerd** [comment]
@ooflorent I really like that you are still working on this, great job. I'm attempting to put together an ECS game engine comprised of the best tools I can find for the job. Previously, I was using my own ECS code but decided to look around for better implementations.

I'm going off on a bit of a tangent here, but I'm interested to see how much performance can be squeezed out of a JS ECS game engine.

I like the sound of the new proposal, though I don't know enough about bitwise operators to understand why that is faster.

I know that using object pooling is important, especially for JS games. Do you think that pooling components should also be something to worry about or is that just overkill? Does this library already do that and I just don't see?

One last question, could you JsDoc the new version? I will help you write documentation and usage examples if I can better understand the code.

EDIT: here is the repo for said engine: https://github.com/flaskio/flask-core/tree/dev

**Comment by ooflorent** [comment]
I'm glad to hear that you consider using makr into your game engine! Of course the new API will be fully documented and would happily accept contributions. I'm not English fluent and writing complete detailed documentation is a bit scary to me.

So basically, why is makr fast? It is because it uses bitwise operations to identify components. Checking against there `constructor`, `prototype` or any other property is expensive for the JS runtime. The dev version uses an internal compiler at runtime to create `Entity` and `EntityManager` classes. Those are optimized to support fast property access. e.g.

``` js
function CompileSetComponent(prop, index) {
  return CompileFunction(`
    function ${prop}$set(component) {
      if (component === null || component === undefined) {
        this._${prop} = undefined
        this._mask = this._mask & ${~(1 << index)}
      } else {
        this._${prop} = component
        this._mask = this._mask | ${1 << index}
      }
    }
  `)
}
```

makr uses `CompileSetComponent` to define component setters.

``` js
// The following compiles a setter for the `position` component and ID 3
CompileSetComponent("position", 3)

// Output
function position$set(component) {
  if (component === null || component === undefined) {
    this._position = undefined
    this._mask = this._mask & -2
  } else {
    this._position = component
    this._mask = this._mask | 1
  }
}
```

This entire compilation process is hidden to the end-developer. When you create the `EntityManager`, makr will compile everything. e.g.

``` js
var em = makr({position: Position, body: Body, sprite: PIXI.Sprite})
```

The API is not currently frozen but here is the last draft:

``` js
declare class Entity<...Cs> & { [_: string]: ...Cs } {
  id: number;
  destroy(): void;
}

declare class EntityManager<...Cs> {
  create(): Entity<...Cs>;
  mask(...components: Array<Class>): number;
  query(mask: number): Array<Entity<...Cs>>;
  reset(): void;
}

makr<...Cs>(components:  { [_: string]: Class<...Cs> }): Class<EntityManager<...Cs>>
```

**Comment by Falconerd** [comment]
Wow, thanks for the thorough reply. I can certainly help you with your English, though from these comments it is not necessary.

I think I understand why that process is faster now, I also read some more about bitwise operations on MDN.

That method of drafting code specification is very interesting, did you learn it somewhere?

My current idea for the end-game-developer to create entities is like this:

``` javascript
// components/body.js
export default class Body {
  constructor(x = 0, y = 0) {
    this.x = x;
    this.y = y;
    this.velx = 0;
    this.vely = 0;
  }
}
```

...etc for other components

``` javascript
// assemblages/dog.js
import { Body, Sprite, Sound } from '../components';

export default [
  new Body(),
  new Sprite('dog.png'),
  new Sound(['bark.mp3', 'wimper.mp3']),
];
```

Then somewhere in the code we have this function

``` javascript
function assemble(components) {
  const entity = em.create();
  for (let component of components) {
    entity.add(component);
  }
  return entity;
}
```

Now, when we want to create an entity, we use this

``` javascript
import Dog from '../assemblages/dog';

const dog = assemble(Dog);

console.log(dog.get(Sound).locations);
// [ 'bark.mp3', 'wimper.mp3' ]
```

With the new version, I'm not quite sure how to make a nice wrapper function...

I know this is outside the scope of makr, but you are the best person to ask as
you are making the library :).

**Comment by ooflorent** [comment]
There are multiple options to write `assemble`. In my opinion, bests are:

**Using entity descriptor**

``` js
type EntityDescriptor = {[_: string]: [Class, Array<any>]}

function assemble(prefab: EntityDescriptor): Entity {
  const entity = em.create()
  for (const key in prefab) {
    const [Component, args] = prefab[key]
    entity[key] = new Component(...args)
  }

  return entity
}

const entity = assemble({
  body: [Body, [50, 50]],
  transform: [Transform2D, [0, 0]],
  sprite: [Sprite, ["dog.png"]],
  sound: [Sound, ["bark.mp3"]]
})
```

**Using entity configurator**

``` js
type EntityConfigurator = (e: Entity): Entity

function assemble(prefab: EntityConfigurator): Entity {
  return prefab(em.create())
}

const entity = assemble((e) => {
  e.body = new Body(50, 50)
  e.transform = new Transform2D(0, 0)
  e.sprite = new Sprite("dog.png")
  e.sound = new Sound("bark.mp3")
  return e
})
```

I really like the last options since it can be used in FP paradigm.

``` js
const movable = (opts) => (e) => { /* do stuff */ }
const controllable = (opts) => (e) => { /* do stuff */ }

const playerPrefab = compose(
  movable({x: 0, y: 1, canFly: true}),
  controllable({keys: ["left", "right"]},
)

const player = assemble(playerPrefab)
```

**Comment by Falconerd** [comment]
Hi @ooflorent, I ended up implementing your last solution and it works quite well! I also did some more reading about functional programming to familiarise myself with the style. Thanks again for your help.
